### ISSUE TITLE
Second python library

### ISSUE THREAD

**Issue by ypid** [martinfilliau/osm-opening-hours#2]
Hi

I created a second python module: https://github.com/ypid/pyopening_hours
Maybe worth adding a link to it if someone is looking for a heavier implementation of http://wiki.openstreetmap.org/wiki/Key:opening_hours:specification :smile:

**Comment by martinfilliau** [comment]
Added link in https://github.com/martinfilliau/osm-opening-hours/commit/a6e33ac6294598d9195f7264e9fc66e3866c5908

**Comment by ypid** [comment]
Finally :wink: Thanks very much :+1:
