### ISSUE TITLE
Please provide license

### ISSUE THREAD

**Issue by k-nut** [martinfilliau/osm-opening-hours#3]
Hey Martin,
I am using your library for a project of mine and would love to be able to install it with `pip`.
Therefore I would really like it if the package were available on PyPI and I was about to publish it when I noticed that you did not include a license in your project. So I would be very thankful if you could provide that.
PS: If you would rather like to publish the package yourself instead of having me do it let me know.

**Comment by martinfilliau** [comment]
Hi @k-nut,
I've just added one. I do not actively work on this project anymore so feel free to publish it to PyPi / contribute! I shall add soon a list of things I was planning to do as improvements or new features.
Cheers!

**Comment by ypid** [comment]
Hey guys. Just a little hint about possible other solutions. @k-nut I am not sure for what you need opening_hours evaluation. I checked this library out a couple of years ago and it implements the most common cases of the [specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification) only. I have worked on a Python binding [pyopening_hours](https://github.com/opening-hours/pyopening_hours) which is ready to be used and available on pypi. Additionally, I have the long term goal to provide a comprehensive native implementation for common programming languages such as Python. You can check my progress about that [in this issue](https://github.com/opening-hours/opening_hours.js/issues/136).

**Comment by martinfilliau** [comment]
@ypid you're right, I've updated the README file https://github.com/martinfilliau/osm-opening-hours/commit/a6e33ac6294598d9195f7264e9fc66e3866c5908 accordingly, also solves #2.

**Comment by k-nut** [comment]
Just FYI the library is now [published on PyPi](https://pypi.python.org/pypi?name=osm_opening_hours&version=0.1.1&:action=display) and can simply be included by running `pip install osm_opening_hours`
