### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by guyarad** [martinfilliau/osm-opening-hours#4]
I have cloned and made some changes for our needs to the project. If this project is still active I would be happy to contribute them back. 
Please let me know.

**Comment by martinfilliau** [comment]
Not active at all!

As written in the README, it should not be considered as a complete parser.

Quite a while ago, https://github.com/opening-hours/pyopening_hours looked like a much better implementation than what I did.

**Comment by guyarad** [comment]
well, the provided Simple API didn't suit my needs... so I extended your implementation. Admittedly, I have modified most of it... thanks for your response anyway.
